# Generated by Django 6.0.1 on 2026-01-10 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('season_year', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('venue', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournament',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organizer', 'status'], name='tournament_organiz_1f6d1f_idx'), models.Index(fields=['slug'], name='tournament_slug_9c2604_idx')],
            },
        ),
    ]
