# Generated by Django 6.0.1 on 2026-01-10 09:27

import auctions.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Auction', max_length=120)),
                ('code', models.CharField(help_text='Shareable code for organizers/viewers to open auction quickly.', max_length=30, unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=auctions.models.auction_banner_upload_to)),
                ('rules', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'auction',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=auctions.models.player_photo_upload_to)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('role', models.CharField(blank=True, choices=[('BAT', 'Batsman'), ('BOWL', 'Bowler'), ('AR', 'All-Rounder'), ('WK', 'Wicket-Keeper')], max_length=8, null=True)),
                ('batting_style', models.CharField(blank=True, max_length=40, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=40, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stats', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SOLD', 'Sold'), ('UNSOLD', 'Unsold'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=12)),
                ('base_price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auctions.auction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auctions.player')),
            ],
            options={
                'db_table': 'auction_lot',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=12, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=auctions.models.team_logo_upload_to)),
                ('purse_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purse_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_players', models.PositiveIntegerField(blank=True, null=True)),
                ('max_players', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('created_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlot')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.team')),
            ],
            options={
                'db_table': 'bid',
            },
        ),
        migrations.AddField(
            model_name='auctionlot',
            name='sold_to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_lots', to='auctions.team'),
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('INJURED', 'Injured'), ('BENCH', 'Bench')], default='ACTIVE', max_length=10)),
                ('jersey_no', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bought_in_auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_players', to='auctions.auction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_entries', to='auctions.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='auctions.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'team_player',
            },
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status'], name='auction_status_ab698f_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['code'], name='auction_code_ded94e_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['tournament', 'is_active'], name='player_tournam_9c5a18_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['tournament', 'role'], name='player_tournam_9b939d_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['tournament', 'is_active'], name='team_tournam_4b4037_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tournament', 'name')},
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['lot', 'bid_time'], name='bid_lot_id_6d63c6_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['team'], name='bid_team_id_b90968_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionlot',
            index=models.Index(fields=['auction', 'status'], name='auction_lot_auction_8ff17e_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionlot',
            index=models.Index(fields=['auction', 'lot_no'], name='auction_lot_auction_2fbb75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionlot',
            unique_together={('auction', 'lot_no'), ('auction', 'player')},
        ),
        migrations.AddIndex(
            model_name='teamplayer',
            index=models.Index(fields=['tournament', 'team'], name='team_player_tournam_3a91ce_idx'),
        ),
        migrations.AddIndex(
            model_name='teamplayer',
            index=models.Index(fields=['team', 'status'], name='team_player_team_id_e76014_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamplayer',
            unique_together={('tournament', 'player')},
        ),
    ]
