# Generated by Django 6.0.1 on 2026-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='designation',
            field=models.CharField(choices=[('PLAYER', 'PLAYER'), ('OWNER', 'OWNER'), ('CAPTAIN', 'CAPTAIN')], default='PLAYER', max_length=50),
        ),
    ]
