# Generated by Django 6.0.1 on 2026-02-09 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_teamplayer_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOT_START', 'Lot Start'), ('BID', 'Bid'), ('MILESTONE_1L', 'Milestone 1L'), ('SOLD', 'Sold'), ('UNSOLD', 'Unsold')], max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('BID', 'Bid'), ('MILESTONE', 'Milestone'), ('SOLD', 'Sold'), ('UNSOLD', 'Unsold')], default='INFO', max_length=12)),
                ('message', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auction_event',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='auctionlot',
            name='auction_lot_auction_2fbb75_idx',
        ),
        migrations.AlterUniqueTogether(
            name='auctionlot',
            unique_together={('auction', 'player')},
        ),
        migrations.AddField(
            model_name='auctionlot',
            name='lot_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='auctionlot',
            index=models.Index(fields=['auction', 'lot_no', 'lot_order'], name='auction_lot_auction_244963_idx'),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='auctions.auctionlot'),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='auctions.player'),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='auctions.team'),
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['auction', 'created_at'], name='auction_eve_auction_aeb4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['auction', 'event_type'], name='auction_eve_auction_c32017_idx'),
        ),
    ]
