# Generated by Django 6.0.1 on 2026-02-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='designation',
            field=models.CharField(choices=[('PLAYER', 'PLAYER'), ('OWNER', 'OWNER'), ('CAPTAIN', 'CAPTAIN'), ('MARQUEE', 'MARQUEE')], default='PLAYER', max_length=50),
        ),
    ]
