# Generated by Django 6.0.1 on 2026-02-11 07:10

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_player_building_player_dob_player_flat_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=auctions.models.player_payment_screenshot_upload_to),
        ),
    ]
