# Generated by Django 6.0.1 on 2026-08-31 08:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_player_jersey_name_player_jersey_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accent_color',
            field=models.CharField(default='#F97316', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #22C55E.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(default='#0F172A', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #22C55E.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='team',
            name='secondary_color',
            field=models.CharField(default='#22C55E', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #22C55E.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='team',
            name='tagline',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.CreateModel(
            name='TeamAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('CO_OWNER', 'Co-Owner'), ('ANALYST', 'Analyst'), ('VIEWER', 'Viewer')], default='OWNER', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to='auctions.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_access_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_access',
                'indexes': [models.Index(fields=['team', 'is_active'], name='team_access_team_id_3a9373_idx'), models.Index(fields=['user', 'is_active'], name='team_access_user_id_1e11ee_idx')],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
