# Generated by Django 6.0.1 on 2026-08-31 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_team_accent_color_team_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamaccess",
            name="linked_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_access_entries",
                to="auctions.player",
            ),
        ),
    ]
